#!/bin/bash
set -e
set -x

# parse arguments
POSITIONAL=()
while [[ $# -gt 0 ]]
do
key="$1"

case $key in
    --docker-image)
    DOCKER_IMAGE="$2"
    shift # past argument
    shift # past value
    ;;
    --base-model-name)
    BASE_MODEL_NAME="$2"
    shift # past argument
    shift # past value
    ;;
    --weights-file)
    WEIGHTS_FILE="$2"
    shift # past argument
    shift # past value
    ;;
    --image-source)
    IMAGE_SOURCE="$2"
    shift # past argument
    ;;
    *)    # unknown option
    POSITIONAL+=("$1") # save it in an array for later
    shift # past argument
    ;;
esac
done


BASENAME_IS=`basename $IMAGE_SOURCE`

# run predictions
DOCKER_RUN="docker run
  --entrypoint entrypoints/entrypoint.predict.cpu.sh \
  -v "$IMAGE_SOURCE":/src/$BASENAME_IS
  -v "$WEIGHTS_FILE":/src/weights.hdf5
  $DOCKER_IMAGE $BASE_MODEL_NAME /src/weights.hdf5 /src/$BASENAME_IS"

eval $DOCKER_RUN


# docker run --entrypoint entrypoints/entrypoint.predict.cpu.sh -v /home/vacingfang/cv/image-quality-assessment/src/tests/test_images/42039.jpg:/src/42039.jpg -v /home/vacingfang/cv/image-quality-assessment/models/MobileNet/weights_mobilenet_technical_0.11.hdf5:/src/weights.hdf5 nima-cpu MobileNet /src/weights.hdf5 /src/42039.jpg
# docker run -ti -d -v /home/vacingfang/cv/image-quality-assessment/src/tests/test_images/42039.jpg:/src/42039.jpg -v /home/vacingfang/cv/image-quality-assessment/models/MobileNet/weights_mobilenet_technical_0.11.hdf5:/src/weights.hdf5 --name=nima-cpu_vac nima-cpu /bin/bash/

